language: ruby
rvm:
- 2.1.2
before_script:
- git clone https://github.com/Kuniri/kuniri.git
- cd kuniri
- gem install yard
- gem install rspec
script:
- rake spec
notifications:
  email:
    - rodrigosiqueiramelo@gmail.com
  on_success: change
  on_failure: always
branches:
  only:
  - master
